In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Praia,CV,2021-07-22 19:35:07,14.9215,-23.5087,81.14,69,20,14.97
1,1,Ushuaia,AR,2021-07-22 19:38:12,-54.8000,-68.3000,42.46,75,40,4.61
2,2,Castro,BR,2021-07-22 19:38:13,-24.7911,-50.0119,60.08,58,0,4.88
3,3,Puerto Ayora,EC,2021-07-22 19:38:13,-0.7393,-90.3518,82.36,87,96,8.01
4,4,Thompson,CA,2021-07-22 19:38:14,55.7435,-97.8558,80.76,54,20,5.75
...,...,...,...,...,...,...,...,...,...,...
555,555,Churapcha,RU,2021-07-22 19:43:41,62.0025,132.4325,61.16,78,100,1.05
556,556,Hegang,CN,2021-07-22 19:43:41,47.4000,130.3667,72.84,79,97,2.64
557,557,Markapur,IN,2021-07-22 19:43:42,15.7333,79.2833,76.51,78,100,20.11
558,558,Manokwari,ID,2021-07-22 19:43:42,-0.8667,134.0833,77.85,82,86,5.97
559,559,Praia,CV,2021-07-22 19:35:07,14.9215,-23.5087,81.14,69,20,14.97

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [15]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [16]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Heatmap of percent Cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [22]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Praia,CV,2021-07-22 19:35:07,14.9215,-23.5087,81.14,69,20,14.97
3,3,Puerto Ayora,EC,2021-07-22 19:38:13,-0.7393,-90.3518,82.36,87,96,8.01
4,4,Thompson,CA,2021-07-22 19:38:14,55.7435,-97.8558,80.76,54,20,5.75
5,5,Avarua,CK,2021-07-22 19:33:27,-21.2078,-159.7750,77.05,83,17,6.91
9,9,Lompoc,US,2021-07-22 19:38:17,34.6391,-120.4579,88.70,72,75,16.11

In [23]:
preferred_cities_df.count()

City_ID       201
City          201
Country       201
Date          201
Lat           201
Lng           201
Max Temp      201
Humidity      201
Cloudiness    201
Wind Speed    201
dtype: int64

In [24]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
0          Praia      CV     81.14  14.9215  -23.5087
3   Puerto Ayora      EC     82.36  -0.7393  -90.3518
4       Thompson      CA     80.76  55.7435  -97.8558
5         Avarua      CK     77.05 -21.2078 -159.7750
9         Lompoc      US     88.70  34.6391 -120.4579
11        Atuona      PF     77.40  -9.8000 -139.0333
14         Kapaa      US     80.58  22.0752 -159.3190
15       College      US     75.58  64.8569 -147.8028
17      Marathon      US     80.24  44.9000  -89.7668
20        Najran      SA     77.65  17.4924   44.1277

In [25]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [37]:
#Iterate through the data frame
for index, row in hotel_df.iterrows():
    #Get the latitude and longitude
    lat = row['Lat']
    lng = row['Lng']
    
    #Add the latitude and longitude to location key for the params dictionary
    params['location'] = f"{lat},{lng}"
    
    #Use the search term: "lodging" and our latitude and longitude
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    #Make request and get the JSON data from the search
    hotels = requests.get(base_url, params=params).json()
    #Grab the first hotel from the results and store the name
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
    except (IndexError):
        print('Hotel not found... skipping.')

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [38]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Praia,CV,81.14,14.9215,-23.5087,LT Aparthotel
3,Puerto Ayora,EC,82.36,-0.7393,-90.3518,Finch Bay Galapagos Hotel
4,Thompson,CA,80.76,55.7435,-97.8558,Burntwood Hotel
5,Avarua,CK,77.05,-21.2078,-159.7750,Paradise Inn
9,Lompoc,US,88.70,34.6391,-120.4579,"Holiday Inn Express Lompoc, an IHG Hotel"
...,...,...,...,...,...,...
551,Ambon,ID,75.34,-3.6954,128.1814,Swiss-Belhotel Ambon
554,Kralendijk,BQ,87.78,12.1500,-68.2667,Divi Flamingo Beach Resort & Casino
557,Markapur,IN,76.51,15.7333,79.2833,VIHARI GRAND INN
558,Manokwari,ID,77.85,-0.8667,134.0833,Swiss Belhotel Manokwari
559,Praia,CV,81.14,14.9215,-23.5087,LT Aparthotel

In [39]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

plant_info = [info_box_template.format(**plant) for plant in nuclear_power_plants]